// <auto-generated />
using System;
using DealerDatabase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DealerDatabase.Data.Migrations
{
    [DbContext(typeof(DealerDbContext))]
    [Migration("20261006135333_Implementation")]
    partial class Implementation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DealerDatabase.Data.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("County")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Line1")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Line2")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Line3")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Town")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyHouseNumber")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FcaReferenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FcaStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("FcaStatusEffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("IcoExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IcoRegistrationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("IncorporationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalName")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RegisteredAddressId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TradingAddressId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VatNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("VatStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredAddressId");

                    b.HasIndex("TradingAddressId");

                    b.ToTable("Dealers");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerOfficer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("AppointedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("DealerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasColumnType("TEXT");

                    b.Property<string>("Occupation")
                        .HasColumnType("TEXT");

                    b.Property<int>("OfficerRole")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ResignedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.ToTable("DealerOfficers");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerTradingName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DealerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.ToTable("DealerTradingNames");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.ImportDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RanAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordsCreated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImportDetails");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.Dealer", b =>
                {
                    b.HasOne("DealerDatabase.Data.Entities.Address", "RegisteredAddress")
                        .WithMany()
                        .HasForeignKey("RegisteredAddressId");

                    b.HasOne("DealerDatabase.Data.Entities.Address", "TradingAddress")
                        .WithMany()
                        .HasForeignKey("TradingAddressId");

                    b.Navigation("RegisteredAddress");

                    b.Navigation("TradingAddress");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerOfficer", b =>
                {
                    b.HasOne("DealerDatabase.Data.Entities.Dealer", "Dealer")
                        .WithMany("Officers")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerTradingName", b =>
                {
                    b.HasOne("DealerDatabase.Data.Entities.Dealer", "Dealer")
                        .WithMany("TradingNames")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.Dealer", b =>
                {
                    b.Navigation("Officers");

                    b.Navigation("TradingNames");
                });
#pragma warning restore 612, 618
        }
    }
}
